### PR TITLE
WIP Add Firebase for High Scores

### PR DESCRIPTION
**Pull request by NickyBobby**
We are able to view high scores
We also have a function that displays a text box once the game is over
Next thing we need is a function that sets the new high score and displays on page

### CODE REVIEW

**Comment by NickyBobby** [comment]
@Tman22 PR is up and I think I'll work on it some more later tonight. If not possibly tomorrow some time.

**Comment by Tman22** [comment]
Thanks man, are you working on it now?

**Comment by NickyBobby** [comment]
I was actually gonna start looking at it again. I just  finished the plan. @Tman22

**Comment by NickyBobby** [comment]
The high score board works now. The only thing is it wasn't triggered when I finished the game. So that will have to be played with a little bit, but otherwise it works. It may not be the prettiest code _but it works!_ Let me know what you think. @Tman22

**Comment by Tman22** [comment]
Looks great, I'll merge it in!

**Pull request merged**
